const Base = require('./Base');
const { avatar } = require('../cdn-utils');

module.exports = class User extends Base {
  /** @type {string} */ username;
  /** @type {string} */ discriminator;
  /** @type {string} */ avatar;
  /** @type {boolean} */ bot;
  /** @type {string} */ banner;
  /** @type {number} */ accent_color;
  avatar_decoration;
  /** @type {number} */ public_flags;
  /** @type {number} */ flags;
  /** @type {string} */ banner_color;
  /** @type {number} */ accent_color;
  /** @type {string} */ tag;

  constructor(data, client) {
    super(data, client);
    for(const k in this)
      if(data[k] !== undefined)
        this[k] = data[k];
    this.tag = `${this.username}#${this.discriminator}`;
    //this.avatar = 
  }

  /**
   * @param {import('../cdn-utils').ImageURLOptions} options Autogenerated by VS Code
   * @returns {string}
   */
  avatarURL(options) {
    return avatar(this.id, this.avatar, options);
  }

  htmlTableRows() {
    const { th, td, tr, img } = require('../html/html-utils');
    const cells = [
      tr(th('id'), td(this.id)),
      tr(th('username'), td(this.username)),
      tr(th('discriminator'), td(this.discriminator)),
      tr(th('avatar'), td(img(this.avatarURL()))),
    ];
    return cells.join('');
  }
};